#!/usr/bin/env python

import rnacounter
from rnacounter import rnacounter_main, parse_args, join

from docopt import docopt

if __name__ == '__main__':
    args = docopt(rnacounter.__doc__, version='1.2')
    if args['join']:
        join([args['TAB']]+args['TAB2'])
    else:
        bamname, annotname, options = parse_args(args)
        rnacounter_main(bamname,annotname, options)

