#!/usr/bin/env python

from rnacounter import rnacounter_main, usage_string, parse_args

from docopt import docopt

if __name__ == '__main__':
    args = docopt(usage_string(), version='0.1')
    bamname, annotname, options = parse_args(args)
    rnacounter_main(bamname,annotname, **options)

