#!/usr/bin/env python

import optparse, json
import bbcflib.bFlatMajor as gMiner

parser = optparse.OptionParser()
for k in ['operation','output','assembly','args']:
    parser.add_option("--"+k)
options, args = parser.parse_args()

kwargs = options.__dict__
if options.args:
    jsonargs = json.loads(kwargs.pop('args'))
    for k,v in jsonargs.iteritems():
        if isinstance(v,basestring): jsonargs[k] = str(v)
    kwargs.update(dict((str(k),v) for k,v in jsonargs.iteritems()))

output = gMiner.run(*args,**kwargs)
if isinstance(output,(list,tuple)):
    print ",".join(output)
else:
    print output
