#!/usr/bin/env python

# Built-in modules #
import optparse, json

# Constants #
doc_url = 'http://bbcf.epfl.ch/bbcflib'
example = "track_convert --assembly=sacCer2 genes.bed genes.sql"

from bbcflib import btrack as track

# All the help messages #
parameters = {
'usage'   : '%prog [options] SOURCE DESTINATION',
'description' : ' Will convert a genomic file from one format to an other.' \
                ' For instance, it can convert a WIG file to a BEDGRAPH file.'\
                ' Usage: %s.'%example,
'option_list' : [optparse.make_option("-a", "--assembly",
                                      help = "The assembly can be any valid GenRep assembly name. For example 'sacCer2'.", default=None),
                 optparse.make_option("-c", "--chrmeta",
                                      help = "Json-formatted chrmeta dictionary.", default=None),
                 optparse.make_option("-1", "--format1",
                                      help = "Format of the first track."),
                 optparse.make_option("-2", "--format2",
                                      help = "Format of the second track.")]}

parser = optparse.OptionParser(**parameters)
options, args = parser.parse_args()
if len(args) != 2: parser.error("You need to specify a SOURCE and a DESTINATION. For instance: " + example)
if options.format1:
    args[0] = (args[0],options.format1)
if options.format2:
    args[1] = (args[1],options.format2)
if options.chrmeta:
    chrmeta = json.loads(options.chrmeta)
track.convert(*args, assembly=options.assembly,chrmeta=chrmeta)
